### ISSUE TITLE
[UNSTABLE] Unable to host a server with mt unstable ship

### ISSUE THREAD

**Issue by Goostave** [PeasantFoundry/Mechtrauma#72] opened 2023-03-29 03:05 UTC
mod list: lua, cs, modding toolkit, mt unstable, and a mt-unstable-converted ship of mine

Already reinstalled lua, deleted mod folder of cs, toolkit, mt-un then reinstalled them, problem remains

process:
host a server
select a mt-un ship (you also can pick one from panman's [Vanilla Submarines Mechtraumized](https://steamcommunity.com/sharedfiles/filedetails/?id=2933544027))
start a campaign
loading screen

then you're kicked back to server browser, and have these errors in the console:
 Level identifier: outpostlevel
Generating an outpost for the start of the level... (Location: Noctae Habitation Outpost, level type: Outpost)
Received STARTGAMEFINALIZE packet. Round init status: WaitingForStartGameFinalize
Task count: 0
Received STARTGAMEFINALIZE packet. Round init status: Started
Received STARTGAMEFINALIZE packet. Round init status: Started
Goostave
Error while reading a message from server. 
Exception thrown while reading segment EntityEvent at position 32.
Inner exception: Message byte position incorrect after reading an event for the entity "Advanced Steam Boiler (ID: 2144)" (ID 2144). The previous entity was "Safety Electrical Panel (ID: 2142)" (ID 2142) Read 160 bits, expected message length was 8 bits.
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 233
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2122
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
ModConfigManager: Patches Unloaded.
[CL CS ERROR] System.Threading.LockRecursionException: Recursive write lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
   at ModdingToolkit.AssemblyManager.CleanupReference(AssemblyLoadContext ctx)
   at System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent()
   at System.Runtime.Loader.AssemblyLoadContext.InitiateUnload()
   at System.Runtime.Loader.AssemblyLoadContext.Unload()
   at ModdingToolkit.AssemblyManager.BeginDispose()
   at ModdingToolkit.PluginHelper.UnloadAssemblies()
   at ModdingToolkit.Bootloader.Stop()
   at Barotrauma.ACsMod.Dispose() in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\Cs\ACsMod.cs:line 36
Stopping Lua...

**Comment by Goostave** [comment] 2023-03-29 05:07
Just tried out dev branch, I can host a server now. The Inner exception part no longer shows up, but the [CL CS ERROR] remains.

[CL CS ERROR] System.Threading.LockRecursionException: Recursive write lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(TimeoutTracker timeout)
   at ModdingToolkit.AssemblyManager.CleanupReference(AssemblyLoadContext ctx)
   at System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent()
   at System.Runtime.Loader.AssemblyLoadContext.InitiateUnload()
   at System.Runtime.Loader.AssemblyLoadContext.Unload()
   at ModdingToolkit.AssemblyManager.BeginDispose()
   at ModdingToolkit.PluginHelper.UnloadAssemblies()
   at ModdingToolkit.Bootloader.Stop()
   at Barotrauma.ACsMod.Dispose() in B:\programming\c#\Barotrauma\Barotrauma\BarotraumaShared\SharedSource\LuaCs\Cs\ACsMod.cs:line 36

I have Dont open console on errors, so it's not a big deal.

**Comment by TBN-MapleWheels** [comment] 2023-03-29 16:10
This error is caused by Modding Toolkit during the shutdown phase because of an issue when unloading assemblies. It shouldn't cause any problems but will be fixed soon.

**Comment by MapleWheels** [comment] 2023-03-30 00:24
Closed as resolved by Modding TK update 0.3.7.

**Closed as completed** 2023-03-30 00:24 UTC
Labels: bug, Modding Toolkit
