### ISSUE TITLE
Chairs of any kind dont work

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#12] opened 2023-01-03 03:57 UTC
Navigation Chair, Gunner's Chair and many other simply not functional!

**Comment by Mannatwo** [comment] 2023-01-03 04:04
from taking a look at the items.xml, it would seem that they are *supposed* to get overriden, but the data is not inside of an override tag.

**Comment by PeasantFoundry** [comment] 2023-01-03 05:58
These are Mechtrauma items, unless vanilla added items of the same name, they shouldn't need override tags. The console in the Navigators Chair is disabled for the moment and it functions just as a regular chair. Since they made it possible to interact with items while sitting in a chair, I've been using it as a chair and clicking on the command console in the background. I will be adding add a a version of the navigators chair with the navigation console included.

**Comment by PeasantFoundry** [comment] 2023-01-03 06:06
Vanilla chairs appear to function normally and the gunners chair appears to functioning as a periscope. Any more details on this issue?

**Comment by PeasantFoundry** [comment] 2023-01-03 21:55
Still cannot reproduce, closing.

**Closed by PeasantFoundry** 2023-01-03 21:55 UTC
