### ISSUE TITLE
c2500D generators do not produce any power

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#37] opened 2023-01-28 12:45 UTC
They dont produce power, neither they consume fuel. But they do consume oxygen and do visual effects + sounds like if they were working!

Steps to reproduce:
1. download this sub
2. launch test mode
3. turn on generator and batteries on nav.console
4. observe generator inner GUI
[Dugong_Mechtrauma.zip](https://github.com/PeasantFoundry/Mechtrauma/files/10527252/Dugong_Mechtrauma.zip)

**Comment by PeasantFoundry** [comment] 2023-01-28 18:32
Any errors in the console?

**Comment by PanmanS** [comment] 2023-01-28 18:44
no

**Comment by PeasantFoundry** [comment] 2023-01-30 15:03
The problem isn't with the generators, it's with your battery setup. The generator is charging your batteries fine. Your batteries aren't powering the submarine:

![image](https://user-images.githubusercontent.com/113934941/215513704-8f778945-5813-42ea-8475-99927546d9ce.png)

**Comment by TBN-MapleWheels** [comment] 2023-02-22 01:01
Closing this issue as there hasn't been any reply.

**Closed by TBN-MapleWheels** 2023-02-22 01:01 UTC
