### ISSUE TITLE
[UNSTABLE] Status monitor, status console, engineering console never have sufficient power

### ISSUE THREAD

**Issue by Goostave** [PeasantFoundry/Mechtrauma#73] opened 2023-03-29 03:30 UTC
mod list: lua, cs, modding toolkit, mt unstable, [Vanilla Submarines Mechtraumized](https://steamcommunity.com/sharedfiles/filedetails/?id=2933544027), a mt-un-converted ship recently finished by me

Already reinstalled lua, deleted mod folder of cs, toolkit, mt-un then reinstalled them, problem remains

process 1:
start a new single player campaign
select a 100% vanilla ship to start, Barsuk for example
loading screen
you go back to the ship, and find navterminal online, but status monitor always "WARNING: INSUFFICIENT POWER"

process 2:
enter sub editor
select a ship from [Vanilla Submarines Mechtraumized](https://steamcommunity.com/sharedfiles/filedetails/?id=2933544027), either Barsuk (no central computer, 1 status console), or Berilia (1 central computer, 1 status console, 1 engineering console) as a control, other ships(including the ship of mine) also have this problem
press test, then find out status console and engineering console never have sufficient power

**Comment by Torca2001** [comment] 2023-03-29 05:03
Couldn't reproduce off current github build, possibly already resolved.

**Comment by Goostave** [comment] 2023-03-29 05:14
> Couldn't reproduce off current github build, possibly already resolved.

Yes, I just tried out dev branch, they're working fine this time.

Another problem, maintenance tablet and medical tablet can't output reports in dev branch, while they can in unstable.
When you press a button, there's only sound, but all black on the tablet.
Errors in the console:
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Shared/helperFunctions.lua:(73,8-34): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Server/mechtrauma.lua:(353,2-75): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Shared/helperFunctions.lua:(73,8-34): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Server/mechtrauma.lua:(422,2-75): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Shared/helperFunctions.lua:(73,8-34): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Server/mechtrauma.lua:(353,2-75): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Server/mechtrauma.lua:(422,2-75): attempt to index a nil value
[SV LUA ERROR] LocalMods/Mechtrauma/Lua/Scripts/Shared/helperFunctions.lua:(73,8-34): attempt to index a nil value

**Comment by MapleWheels** [comment] 2023-03-29 14:26
Let me look into this.

**Comment by TBN-MapleWheels** [comment] 2023-03-29 16:07
Fixed in #74 .

**Closed as completed by TBN-MapleWheels** 2023-03-29 16:07 UTC
Labels: bug
